### ISSUE TITLE
advertisingTrackingEnabled not working on Android

### ISSUE THREAD

**Issue by smileygamer** [distriqt/ANE-IDFA#1]
@marchbold On all our Android devices we found that IDFA.service.advertisingTrackingEnabled always returns true, despite having opted out of ads personalization. Is this a bug?

![screenshot_google play services](https://user-images.githubusercontent.com/12551463/46206415-388ffe80-c324-11e8-90b3-1801b387925b.jpg)

**Comment by marchbold** [comment]
The `advertisingTrackingEnabled` has only been implemented on iOS. Will look into adding it into the Android version in a future release. You can contact us directly if you need this urgently.

**Comment by marchbold** [comment]
The isLimitAdTracking flag for Android has been added to the event. 

See the updated docs on https://github.com/distriqt/ANE-IDFA/wiki/u.Get-Advertising-Identifier
