### ISSUE TITLE
It don't work on IOS 16.5 

### ISSUE THREAD

**Issue by zengqingyong** [distriqt/ANE-IDFA#13]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Environment 

- AIR SDK 50.2.2.5: 
- Device 12 proMax: 
- Device version: 16.5 
- Development IDE: 
- Development OS:

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Can you elaborate some more? What isn't working? 

It is working in our tests on 16.5

**Comment by zengqingyong** [comment]
When I use the debug mode and install the application, it can display the prompt whether to allow tracking. When I uninstall the application and reinstall it, use the dev mode, it does not display this information.

**Comment by marchbold** [comment]
Are you certain the permission for the app hasn't been retained in that scenario. I don't quite understand the process you are describing but if the permission has been set already the dialog won't appear.

**Comment by zengqingyong** [comment]
![IOS 14 7](https://github.com/distriqt/ANE-IDFA/assets/39934711/d6cb07fc-a79b-445d-a85d-7ebbe39a88f3)
![Ios 16 5](https://github.com/distriqt/ANE-IDFA/assets/39934711/efb45cde-20e2-44e7-943e-f50f642011ce)

Look at these two pictures, one with this option and one without this option

**Comment by marchbold** [comment]
Have you requested authorisation before looking at the settings? I don't believe it is displayed until you have requested the auth.

**Comment by zengqingyong** [comment]
Yes , i have open the APP ,but it don't  show me Tracking allowed or not

**Comment by zengqingyong** [comment]
If I use debug mode to package with Adobe Air every time i install the App it can show me Tracking allowed or not,but use Dev  package App, open the APP  it can't show

**Comment by zengqingyong** [comment]
Just on IOS 16.5

**Comment by marchbold** [comment]
Are you calling the authorisation request though? Opening the app might not be enough. 

https://docs.airnativeextensions.com/docs/idfa/get-advertising-identifier#requesting-authorisation

**Comment by zengqingyong** [comment]
IDFA.service.requestAuthorisation(
						function ( status:String ):void 
						{
							trace("IDFA.service::"+status);
							if (status == TrackingAuthorisationStatus.AUTHORISED)
							{
								IDFA.service.getIDFA();
							}
							showAccept();
						}
				);

Yes, I have requested permission, but I found the key point, if I uninstall the APP and restart the phone and then reinstall the APP it can show whether tracking or not, if I do not restart the phone, uninstall the APP and install the APP again it will not show whether tracking or not

**Comment by marchbold** [comment]
Hmm sounds like a bug in iOS. Not really something we can address here.

**Comment by zengqingyong** [comment]
But unity doesn't have that problem!

**Comment by marchbold** [comment]
How are you installing the app then? It must be a difference between the way you are installing it and the way Unity uses Xcode.  

I'm not exactly sure what the issue is though, if it works in production and is just a quirk of the installation method it's not really an issue with the extension but with the way iOS is detecting changes in the installed debug app.

**Comment by zengqingyong** [comment]
Could this be related to AirSDK? Its iphoneosSDK version is 16.2

**Comment by marchbold** [comment]
Maybe, but I doubt it. More likely one of the reasons I mentioned.

**Comment by zengqingyong** [comment]
var status:String = IDFA.service.authorisationStatus();
				idfaTxt1.text = status;
				if (status == TrackingAuthorisationStatus.NOT_DETERMINED)
				{
					IDFA.service.requestAuthorisation(
						function ( status:String ):void 
						{
							trace("IDFA.service::" + status);
							idfaTxt.text = status;
							if (status == TrackingAuthorisationStatus.AUTHORISED)
							{
								IDFA.service.getIDFA();
							}
						}
				);
				}
![1111](https://github.com/distriqt/ANE-IDFA/assets/39934711/998feab1-5c6d-4917-9700-b1106e440e23)

Today I find that,IDFA.service.requestAuthorisation() look like not work

**Comment by marchbold** [comment]
Try renaming the variables, you have duplicate definition of `status:String`

**Comment by zengqingyong** [comment]
I made a try, and I found that I couldn't call authorisationStatus() when I first entered the program, and the call would have the problem I mentioned, but after a delay of 0.5 seconds, everything was fine, and I suspected that this call needed to be delayed

**Comment by marchbold** [comment]
Yes, anything that presents a ui needs to await AIR initialisation completely. Generally the added to stage event is a good place.

**Comment by zengqingyong** [comment]
Yes,thank you for your help!
