### ISSUE TITLE
Type was not found or was not a compile-time constant: ConsentInformationEvent.

### ISSUE THREAD

**Issue by hadisn** [distriqt/ANE-IDFA#14]
Solved this but now i see following error:
UMP requires the Google Ad Identifier library. We suggest you install the IDFA extension, 

but I added IDFA already...

**Comment by marchbold** [comment]
This can happen if you don't correctly package the extension with your application. Have you added the extension id to your app descriptor?

**Comment by marchbold** [comment]
Can you elaborate some more, are you talking about consent from UMP? Which forms are you using? This is likely internal to the AdMob SDK so outside our direct control, what references do you have for other people experiencing the same issue?

**Comment by hadisn** [comment]
Yes I am talking about ump. For example: if user click manage options, then confirm button, ads will not show anymore, I tried to request nonpersonalized ads but nothing…

People also complain here: https://support.google.com/admob/thread/224109149/my-app-does-not-load-ads-when-gdpr-consent-is-not-given?hl=en

**Comment by marchbold** [comment]
This is all internal to the AdMob SDK so outside our control and seems to be occurring for multiple users so we'll just have to wait for a response / fix from Google.
