### ISSUE TITLE
isLimitAdTrackingEnabled is always true on IOS

### ISSUE THREAD

**Issue by GithubProgrammer** [distriqt/ANE-IDFA#15]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Expected behaviour
isLimitAdTrackingEnabled should return false when permission is allowed either at the beginning of the app or from the settings page.

##### Actual behaviour
isLimitAdTrackingEnabled is always returning true on IOS regardless of permission being allowed or not.

##### Environment 

- AIR SDK version: 50.2.1
- Device OS: IOS
- Device version: 16.5.1
- Development IDE: Flash Develop
- Development OS: Windows

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Can you elaborate on the process you are going through here and exactly what setting you are changing? 

There have been reports of similar behaviour for other ios developers in the past when using development apps and certain versions of iOS. Sometimes a device reboot was required during testing. Personally I haven't encountered this behaviour on our test devices.

**Comment by GithubProgrammer** [comment]
I am having some problem on Consent part of the Adverts ANE. Upon inspecting, I could find that isLimitAdTrackingEnabled is always returned as true on IOS device. I am not changing any settings, while debugging I could find this to be true no matter even if I allow the permission at the beginning or allow through the settings. 

On Android, this is returning false however, could not load the consent form. This should be another topic though.

I will check with rebooting the device once.

**Comment by GithubProgrammer** [comment]
After reboot, it is still not working. isLimitAdTrackingEnabled is always true. What else can I check ??

**Comment by marchbold** [comment]
I'm not sure, I haven't encountered this behaviour on a device before.
