### ISSUE TITLE
App Store "Invalid architectures" issue

### ISSUE THREAD

**Issue by aramsargsyan86** [distriqt/ANE-IDFA#2]
When I tried to upload release build to app store, this error occurred "Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools".
Please fix this ASAP.

- IPHONE OS SDK version: 12.1
- AIR SDK version: 32.0.0.103
- Device OS: Mojave 10.14.3
- Device version: 
- Development IDE: Intellij IDEA
- Development OS: IOS

**Comment by marchbold** [comment]
Let me know if this update resolves it for you

**Comment by aramsargsyan86** [comment]
Everything is Perfect now,
Thanks a lot Michael for fixing this in such short period of time!
