### ISSUE TITLE
ld: framework not found AppTrackingTransparency

### ISSUE THREAD

**Issue by uerceg** [distriqt/ANE-IDFA#5]
Hey guys,

Opening an issue in here as well. Summary: https://community.adobe.com/t5/air/adobe-air-sdk-ios-14-support/m-p/11680749?page=1#M56688

**Comment by marchbold** [comment]
The AppTrackingTransparency framework is a new framework in the iOS 14 SDK. 

AIR 33.1.1.259 does not include the iOS 14 SDK so you need to include a reference to it through the `platformsdk` option: http://docs.airnativeextensions.com/docs/tutorials/ios-sdk-custom 

Or use AIR 33.1.1.300 or higher.

**Comment by uerceg** [comment]
Amazing, thank you for your advice. Will check this ASAP and update in here if it worked.

**Comment by uerceg** [comment]
And thank you one more time! It works now pretty good. I have no idea how I ended up not having 33.1.1.300 when I downloaded latest version yesterday from download page. 🤷‍♀️ Nevertheless, thank you for your help. Cheers!

**Comment by marchbold** [comment]
Just FYI, 33.1.1.345 was released today, and I'd suggest moving to it as 33.1.1.300 contains a lot of issues.

**Comment by uerceg** [comment]
Thank you for an update! 🍺
