### ISSUE TITLE
It always returns Authorized without showing a popup

### ISSUE THREAD

**Issue by leossmith** [distriqt/ANE-IDFA#7]
So I am trying to implement this in one of my apps, as I was asked by apple to have the App Tracking Transparency. ANE seems to be implemented as should but I never get the popup asking for permissions. Furthermore, it always returns "Authorized" on my testing device.

##### Expected behaviour
Should so popup and let the user decided if they want to consent or not. 

##### Actual behaviour
No popup, always returns "Authorized"

##### Environment 

- AIR SDK version: 33.1.1.533
- Device OS: iOS 12.5.x
- Device version: iPad Mini 2 and Apple's Review device
- Development IDE: Intellij
- Development OS: Windows 10

**Comment by marchbold** [comment]
iOS 12.5 doesn't support ATT so this is expected.

You will only see ATT on iOS 14.5+

**Comment by leossmith** [comment]
That was my first thought, but I got a rejection from apple, saying that this is not included in their testing device - Device type: iPad - OS version: iOS 14.5.

I have this in my descriptor:

```
<key>NSUserTrackingUsageDescription</key>
		<string>This identifier will be used to deliver personalized experience to you.</string>
```

And this in the start of my app:

```
IDFA.service.requestAuthorisation(
                function( authorisationStatus:String ):void
                {
                    trace( 'checked again'+authorisationStatus );
                }
        ); 
```

That should show the appropriate popup?

**Comment by marchbold** [comment]
that should be all you need, it's passed review in several of our apps.

 have you got a device to test on?

**Comment by leossmith** [comment]
I don't have access to a physical device with 14.5 installed, I will try the simulator and amazon device farm.

**Comment by marchbold** [comment]
Okay, let me know how it goes.

**Comment by leossmith** [comment]
Does this ANE (or any ane) work with iPhone Simulator? I am getting an error for architecture which makes me think it doesnt work.

**Comment by leossmith** [comment]
After testing on Device Farm, it looks like the popup appears as should. Not sure why Apple is rejecting the app.

**Comment by marchbold** [comment]
We had a similar rejection on an app, double checked everything and resubmitted the exact same app and they approved it... Sometimes I think they are being lazy...

**Comment by leossmith** [comment]
They sure are... Submitted the app 5 times, always rejected. Posted them screenshots and they said they might missed that.... Lost me 3 days..
