### ISSUE TITLE
ld: unexpected token: !tapi-tbd for architecture arm64 Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by jimmymjing** [distriqt/ANE-IDFA#8]
Hello, I'm getting the error `ld: unexpected token: !tapi-tbd for architecture arm64
Compilation failed while executing : ld64` when I compile my game after adding iOS SDK to my IDE.
I read through the adding iOS SDK's tutorial provided by Distriqt and simply downloaded the SDK your provided.
The thing is that if I remove the iOS SDK, I don't have any issues to compile my game and IDFA ANE works as well, but I still wish to include iOS SDK in as it may get required for your rest ANEs.

##### Environment 

- AIR SDK version: AIR 33.1.1.575
- Device OS: ios 14
- Device version: iphoneX
- Development IDE: flash builder 4.7
- Development OS: windows 7

**Comment by marchbold** [comment]
You don't currently need the iOS SDK for any of our ANEs. The latest AIR SDK has a very recent version included. Currently I'd suggest not using the platformsdk for iOS.

**Comment by jimmymjing** [comment]
Thanks so much!! It might be useful to add this piece of information on the tutorial page of adding iOS SDK.

**Comment by marchbold** [comment]
Yeah it's a hard one to keep up with as it is a constantly changing system.
