### ISSUE TITLE
for iOS 15.0.1 IDFA ane is not working

### ISSUE THREAD

**Issue by jabirraju** [distriqt/ANE-IDFA#9]
for iOS 15.0.1 IDFA ane is not working, so app update is rejected by apple. by giving following info. IDFA ane was working fine for lower iOS version. but when i updated my iphone to 15.0.1, it is not showing popup for user consent.

Oct 7, 2021 at 7:20 PM
From Apple
2. 1 Performance: App Completeness
Hello,

Thank you for your message.

It would be appropriate to refer to the available documentation to confirm App Tracking Transparency has been correctly implemented.

In particular, review the specifications for the requestTrackingAuthorization(completionHandler:) type method, make any necessary adjustments, and test your app on a device running iOS 15.

You may also ask a question on the Apple Developer Forums to consult with fellow developers and Apple engineers.

If you need code-level support, your questions would be best addressed by Apple Developer Technical Support who can provide discrete code-level assistance for Apple frameworks, APIs, and tools. You may contact them directly by filing a Technical Support Incident.

We look forward to reviewing your app once the appropriate changes have been made.

Best regards,

App Store Review

**Comment by marchbold** [comment]
What happens in your app when you trigger the authorisation request?

Can you post the logs from your device?

https://docs.airnativeextensions.com/docs/tutorials/device-logs

**Comment by marchbold** [comment]
https://forum.starling-framework.org/d/23380-apptrackingtransparency-requester-different-behaviour-since-ios-15/2
